#  v0.30.2-fat
ARG FOREST_VERSION=v0.30.2-fat
FROM ghcr.io/chainsafe/forest:${FOREST_VERSION}
ENV DEBIAN_FRONTEND="noninteractive"

# Install binary dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      aria2 \
      bc \
      curl \
      jq \
      python3 \
      python3-pip \
      unzip \
      wget  \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt \
    && rm -f requirements.txt

# Basic verification of dynamically linked dependencies
RUN forest -V \
    && forest-cli -V \
    && forest-tool -V \
    && jq -V \
    && python3 -V

# RUN groupadd --gid 1001 forest \
#  && useradd --uid 1001 --gid 1001 --create-home --shell /bin/bash forest
#
# USER forest
ENTRYPOINT ["/bin/bash"]
