ARG FOREST_VERSION=main

FROM golang:1.24-bookworm AS build-env
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# install dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y build-essential clang-14 curl git ca-certificates
RUN update-ca-certificates
ENV CC=clang-14 CXX=clang++-14

# install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile minimal
ENV PATH="/root/.cargo/bin:${PATH}"

# Download Forest source code
WORKDIR /src
RUN git clone --depth 1  \
      https://github.com/ChainSafe/forest.git forest \
    && cd forest \
    && git fetch --depth 1 origin ${FOREST_VERSION} \
    && git checkout ${FOREST_VERSION}

# Install Forest. Move it out of the cache for the prod image.
WORKDIR /src/forest
RUN --mount=type=cache,sharing=private,target=/root/.cargo/registry \
    --mount=type=cache,sharing=private,target=/root/.rustup \
    --mount=type=cache,sharing=private,target=/forest/target \
    make install-lto-fat && \
    mkdir /forest_out && \
    cp /root/.cargo/bin/forest* /forest_out

FROM ubuntu:24.04 AS slim-image

ENV DEBIAN_FRONTEND="noninteractive"
# Install binary dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      bc \
      ca-certificates \
      curl \
      jq \
      unzip \
    && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates

# Install awscli
RUN \
  curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip" \
  && unzip -qq awscliv2.zip \
  && ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update > /dev/null \
  && rm -rf \
    /usr/local/aws-cli/v2/current/dist/aws_completer \
    /usr/local/aws-cli/v2/current/dist/awscli/data/ac.index \
    /usr/local/aws-cli/v2/current/dist/awscli/examples \
  && find /usr/local/aws-cli/v2/current/dist/awscli/data -name 'completions-1*.json' -delete \
  && find /usr/local/aws-cli/v2/current/dist/awscli/botocore/data -name examples-1.json -delete


# Copy forest daemon and cli binaries from the build-env
COPY --from=build-env \
    /forest_out/* /usr/local/bin/

# Basic verification of dynamically linked dependencies
RUN forest -V \
    && forest-cli -V \
    && forest-tool -V \
    && aws --version \
    && jq -V

ENTRYPOINT ["forest"]
